import type { Metadata } from "next";
import { Crimson_Text } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const crimson = Crimson_Text({
  subsets: ["latin"],
  weight: ["400", "600", "700"],

});

export const metadata: Metadata = {
  title: "BoatingX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={crimson.className}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
